spring:
  datasource:
    url: jdbc:h2:mem:testingdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
      show-sql: true
      properties:
        hibernate:
          dailect: org.hibernate.dialect.H2Dialect
          format-sql: true
      hibernate:
        ddl-auto: create
  h2:
    console:
      enabled: true
server:
  port: 8090