server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:marketdb
    driverClassName: org.h2.Driver
    username: sa
    password: 
  jpa:
    show-sql: true
    properties:
      hibernate:
        dailect: org.hibernate.dialect.H2Dialect
        format_sql: true
    hibernate:
        ddl-auto: create-drop
  h2:
    console:
      enabled: true